# 1、基础镜像
FROM jenkins/jenkins:centos7

# 2、镜像作者和电子邮箱
MAINTAINER chenlong "chenlong220192@gmail.com"

# 切换root用户
USER root

# 使用root权限安装相关工具
RUN yum update -y && \
    yum install -y sudo telnet && \
    yum clean all

# 给jenkins用户sudo权限
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# 切换jenkins用户
USER jenkins

# 构建命令
#### docker build -f Dockerfile-centos7-jenkins --rm -t base/centos7-jenkins .
