version: '3.1'

services:

  ghost:
    image: ghost
    restart: always
    container_name: ghost
    ports:
      - 2368:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: chenlong
      database__connection__database: ghost

  db:
    image: mysql:5.7.28
    restart: always
    container_name: mysql
    ports:
      - 9200:3306
    volumes:
      - ~/data/docker/ghost/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: chenlong
      MYSQL_DATABASE: ghost
    command: --default-authentication-plugin=mysql_native_password
