version: '2.1'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    networks:
      - prom_bridge
    ports:
      - 9090:9090
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
networks:
  prom_bridge:
    name : prom_bridge
    driver: bridge
